#!/bin/sh
if ! command -v brew > /dev/null; then 
	echo "Installing homebrew"
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	eval "$(/opt/homebrew/bin/brew shellenv)"
fi
brew bundle
fish_path=$(which fish)
chpass -s $fish_path $(whoami)
echo "Update Terminal's preferences to use $(which fish) as default shell"
